### ISSUE TITLE
Input "places-auto-complete" + <ngui-map> makes map not displayed.

### ISSUE THREAD

**Issue by comemanu** [ng2-ui/map#133] opened 2017-04-23 14:01 UTC
Input with directive "places-auto-complete" in conjonction with a map
results with the map invisible.

We can see this behavior even in this demo : 
https://rawgit.com/ng2-ui/map/master/app/index.html#/places-auto-complete

**Comment by allenhwkim** [comment] 2017-04-25 20:49
@comemanu thanks for reporting this. I thought I made a fix for this, but I will take a look into it again. @aitboudad do you have time?

**Comment by aitboudad** [comment] 2017-04-26 09:27
No, sorry!

**Comment by jmlw** [comment] 2017-04-26 13:57
I was just about to report this same issue. I created a plunkr to demonstrate the issue as well:

https://plnkr.co/edit/fiPfH9dLHQKxOibPjq76?p=preview

**Comment by yasserelsayed** [comment] 2017-04-29 10:50
if you switch it and put your map before autocomplete input it will work good :)

**Comment by jmlw** [comment] 2017-05-01 03:17
A viable workaround, it also points to the likely hood that this issue is caused by an ordering problem loading the google maps API and or the modules loaded by the API. Looking back at the commit history for when this issue happened previously, there was some rework around how the google maps API was loaded, and how a reference to it is stored. I haven't had enough time to dig in, but it looks like that's where the issue lies. It's possible that other combinations of components will cause the same issue.

**Comment by aitboudad** [comment] 2017-05-01 09:49
Hi, I'll try to find a solution today, stay tunned!

**Comment by aitboudad** [comment] 2017-05-01 14:41
see #138

**Closed** 2017-05-01 16:24 UTC
