### ISSUE TITLE
Anormal CPU usage

### ISSUE THREAD

**Issue by rsaenen** [ng2-ui/map#218] opened 2017-11-10 15:28 UTC
**Issue description**
I have a map with a few markers (~5), when I click on marker the cpu is always working even when the map is longer displayed.   
I use `ChangeDetectionStrategy.OnPush` and only markForCheck when I get my data.
```html
<ngui-map
    [center]="filters.city.lat + ', ' + filters.city.lng"
    zoom="12">
    <marker *ngFor="let place of places"
        [position]="place.lat + ', ' + place.lng"
        (click)="onSelectPlace(place)">
    </marker>
</ngui-map>
```

```typescript
    /**
     * On select a place event handler.
     * Emits the selection.
     * @param place
     */
    public onSelectPlace(place: Place): void {
        // this.selectPlace.emit(place);
    }
````

**Current behavior**
I've checked with chrome performance tab the activity of my application:
![cpu_usage](https://user-images.githubusercontent.com/5824307/32171415-47681aa8-bd78-11e7-82ac-60591a0770cf.png)   

The map is loaded, I do nothing and I can't see no activity. I click on a marker at 6000ms and after I do nothing but I can see an activity even after angular lifecycle OnDestroy.   

**Expected/desired behavior**
No activity after I clicked on a marker after a few second.

**Comment by allenhwkim** [comment] 2017-11-10 17:13
`(click)`,  this is also a angular event, which is not a  google maps event. As per design, Marker is directive without any DOM element.

Does a marker has click event? yes it does.

Hmm,

Code to add event listener
https://github.com/ng2-ui/map/blob/master/src/services/ngui-map.ts#L17

Code to unregister map object
https://github.com/ng2-ui/map/blob/master/src/directives/base-map-directive.ts#L73

Before I fix this, I need to eliminate the factor of Google maps bug, or Angular bug.
Please do me a favour. Can you run it with purely with Google maps, and check the same thing?

**Comment by rsaenen** [comment] 2017-11-11 10:01
Thanks for this informations, here is a new screenshot of the activity with aot and env prod:
![cpu_usage](https://user-images.githubusercontent.com/5824307/32688357-842ee146-c6cf-11e7-952b-08feb3c8c165.png)

I'll do the same thing with pure javascript and Google maps.

**Comment by rsaenen** [comment] 2017-11-11 10:23
An example with pure Google maps:
![cpu_usage2](https://user-images.githubusercontent.com/5824307/32688520-7dd7edda-c6d2-11e7-9c1a-f84bc6df9f5c.png)
The click is around 5 sec.

I can see a bit less activity but the activity won't stop. 
I saw that when I move the center of the map, the activity going down.

**Comment by allenhwkim** [comment] 2017-11-12 02:22
So, it does happen with pure google maps? 
AFAIK, we cannot stop the google maps instance. There is bug of google maps regarding GC.

**Comment by aitboudad** [comment] 2017-12-21 23:19
duplicate of #163

**Closed by aitboudad** 2017-12-21 23:19 UTC
